---
title: "Exploring ggplot"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
```

```{r}
head(mpg)
```

```{r}
#displacement vs highway
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy))

ggplot(data = mpg)+
  geom_point(mapping = aes(x=hwy,y=cyl))

ggplot(data = mpg)+
  geom_point(mapping = aes(x=class,y=drv))

#displacement vs highway with color as class
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy, color = class))

#displacement vs highway with size as class
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy, size = class))

#displacement vs highway with color gradient as class
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy, alpha = class))

#displacement vs highway with shape as class
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy, shape = class))

ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy) , color = "red")

#shapes range from 0 - 20
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy) , shape = 4)
```
```{r}
#displacement vs highway with color as class
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy, color = cty))

#displacement vs highway with size as class
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy, size = cty))

#displacement vs highway with color gradient as class
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy, alpha = cty))

```
```{r}
#multiple aesthetics
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy, size = cty, color = class,shape=drv))

```

```{r}
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy) , shape = 13, stroke = 0.1)
```

```{r}
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy,color=displ<5))
```

```{r}
#adding facets
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy) , shape = 1)+
  facet_wrap(~class , nrow=2)
```

```{r}
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy) , shape = 1)+
  facet_grid(drv~cyl)
```
```{r}
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy) , shape = 1)+
  facet_grid(.~cyl)
```
```{r}
ggplot(data = mpg)+
  #geom_point(mapping = aes(x = displ,y = hwy))
  geom_smooth(mapping = aes(x = displ,y = hwy))
```

```{r}
ggplot(data = mpg)+
  #geom_point(mapping = aes(x = displ,y = hwy))
  geom_smooth(mapping = aes(x = displ,y = hwy, linetype = drv))
```
```{r}
ggplot(data = mpg)+
  geom_point(mapping = aes(x = displ,y = hwy,color=drv))+
  geom_smooth(mapping = aes(x = displ,y = hwy, linetype = drv))
```
```{r}
ggplot(data = mpg)+
  geom_smooth(mapping = aes(x = displ,y = hwy))

ggplot(data = mpg)+
  geom_smooth(mapping = aes(x = displ,y = hwy, linetype = drv, group = drv))

ggplot(data = mpg)+
  geom_smooth(mapping = aes(x = displ,y = hwy, color=drv))
```
```{r}
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ, y=hwy))+
  geom_smooth(mapping = aes(x=displ, y = hwy))
```
```{r}
ggplot(data=mpg,mapping = aes(x=displ,y=hwy))+
  geom_point()+
  geom_smooth()
```
```{r}
ggplot(data=mpg,mapping = aes(x=displ,y=hwy))+
  geom_point(mapping = aes(color=class))+
  geom_smooth()
```
```{r}
ggplot(data=mpg,mapping = aes(x=displ,y=hwy))+
  geom_point(mapping = aes(color = class))+
  geom_smooth(data = filter(mpg, class == "subcompact"),se=FALSE) # SE - standard error
```
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) + 
  geom_point(show.legend = FALSE) + 
  geom_smooth(se = FALSE,show.legend = FALSE)
```

```{r}
ggplot(data = mpg) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, color = drv)
  )
```

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color=drv))
```

