---
title: "exploring_ggplot_with_diamonds"
output:
  html_document:
    df_print: paged
---

```{r}
library(ggplot2)
library(tidyverse)
```

```{r}
head(diamonds)
```

```{r}
ggplot(data = diamonds)+
  geom_bar(mapping = aes(x=cut))
```
```{r}
ggplot(data = diamonds)+
  stat_count(mapping = aes(x=cut))
```

```{r}
demo <- tribble(
  ~cut,         ~freq,
  "Fair",       1610,
  "Good",       4906,
  "Very Good",  12082,
  "Premium",    13791,
  "Ideal",      21551
)

ggplot(data = demo) +
  geom_bar(mapping = aes(x = cut, y = freq), stat = "identity")
```

```{r}
ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )
```
```{r}
ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth)
  )
```
```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut,color=cut))
ggplot(data = diamonds,group = 1) + 
  geom_bar(mapping = aes(x = cut, fill = cut))
ggplot(data=diamonds)+
  geom_bar(mapping = aes(x = cut, fill = clarity))
```


```{r}
ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + 
  geom_bar(alpha = 1/5, position = "identity")
ggplot(data = diamonds, mapping = aes(x = cut, colour = clarity)) + 
  geom_bar(fill = NA, position = "identity")
```

```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity),position="fill")
```
```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), position = "jitter")
```
```{r}
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + 
  #geom_point(positio="jitter")
  geom_point()+
  geom_jitter(width=0.25,height = 0.4)
```
```{r}
ggplot(mpg, aes(cty, hwy)) +
 geom_count()
```
```{r}
ggplot(data = diamonds)+
  geom_bar(aes(x = cut, fill = clarity))+
  coord_polar()
```
```{r}
ggplot(data = mpg,aes(y=hwy,x=class))+
  geom_boxplot()
```
```{r}
bar <- ggplot(data = diamonds) + 
  geom_bar(
    mapping = aes(x = cut, fill = cut), 
    show.legend = FALSE,
    width = 1
  ) + 
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

bar + coord_flip()
bar + coord_polar()
```
```{r}
library(mapdata)
nz <- map_data("nz")

ggplot(nz , aes(long,lat,group=group))+
  geom_polygon(fill = "white", color = "black")

ggplot(nz , aes(long,lat,group=group))+
  geom_polygon(fill = "white", color = "black")+
  coord_quickmap()
```
```{r}
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_point() + 
  geom_abline() +
  coord_fixed()
```

``` {r}
 # ggplot(data = <DATA>) + 
 #  <GEOM_FUNCTION>(
 #     mapping = aes(<MAPPINGS>),
 #     stat = <STAT>, 
 #     position = <POSITION>
 #  ) +
 #  <COORDINATE_FUNCTION> +
 #  <FACET_FUNCTION>
```